# Generated by Django 3.0.6 on 2023-10-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_studentfeelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeelogs',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
