# Generated by Django 3.0.6 on 2023-10-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20231006_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='due_amount',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='fee',
            name='pay_amount',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
