# Generated by Django 3.0.6 on 2023-10-06 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20231006_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'managed': True, 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='attendancereport',
            options={'managed': True, 'verbose_name': 'AttendanceReport', 'verbose_name_plural': 'AttendanceReports'},
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='tbl_attendance',
        ),
        migrations.AlterModelTable(
            name='attendancereport',
            table='tbl_attendance_report',
        ),
        migrations.CreateModel(
            name='NotificationAccountant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('accountant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.Accountant')),
            ],
            options={
                'verbose_name': 'NotificationStaff',
                'verbose_name_plural': 'NotificationStaffs',
                'db_table': 'tbl_notification_accountant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeaveReportAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_date', models.CharField(max_length=255)),
                ('leave_message', models.TextField()),
                ('leave_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('accountant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.Staffs')),
            ],
            options={
                'verbose_name': 'LeaveReportAccount',
                'verbose_name_plural': 'LeaveReportAccount',
                'db_table': 'tbl_leave_report_account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FeedBackAccountant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('acccountant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.Accountant')),
            ],
            options={
                'verbose_name': 'FeedBackAccount',
                'verbose_name_plural': 'FeedBackAccount',
                'db_table': 'tbl_feedback_acccount',
                'managed': True,
            },
        ),
    ]
