# Generated by Django 3.0.6 on 2023-10-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_auto_20231006_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackaccountant',
            old_name='acccountant_id',
            new_name='accountant_id',
        ),
    ]
