# Generated by Django 3.0.6 on 2023-10-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_auto_20231008_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='last_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
