# Generated by Django 3.0.6 on 2023-10-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_fee_last_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='pay_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
