# Generated by Django 3.0.6 on 2023-10-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_auto_20231008_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
